kumahq/envoy-builds

.github/workflows/ci.yaml
In preparation for replacing this workflow.
=> ci(.github): only run CI workflow on workflow_dispatch

.github/workflows/build.yaml
`arm64` and `amd64` install `homebrew` packages to different locations, apparently. And when we run `ssh` like this, the command is executed directly so there's no sourcing of `~/.bashrc` or anywhere where `homebrew` will have added its `bin` to `$PATH.
When we move the envoy builds scripts into this repo we can clean all of this up.
=> fix: add homebrew to PATH on darwin

terraform/main.tf
With the newer version of terraform build fails because of https://github.com/terraform-aws-modules/terraform-aws-vpc/releases. In 5.0.0 value was removed.
=> chore(deps): upgrade provider version

terraform/README.md
When you provide a target `//source/exe:envoy-static` to the build script it won't build tests and build takes much less time.
=> docs(windows): added target to windows build command

scripts/build_darwin.sh, terraform/macos.tf
It's not clear yet why suddenly builds of Envoy for darwin/amd64 started to fail. It's not connected to image version(ami) because I've tried the same as we used previously with the previous envoy version that succeded but now it doesn't work. 
I've found out that after installation of wget in `/usr/local/include/` there is a link to `openssl` linking headers files. That causes that during envoy build, bazel takes these header files to build external dependencies. These header files are newer than the dependency is using and that is causing the error. Something in the installation of the dependency has changed.
=> fix(darwin/amd64): remove /usr/local/include/openssl to pass the build

README.md
Instead of https://github.com/kumahq/envoy-builds/pull/37
proof that it passes e2e tests: https://github.com/kumahq/kuma/pull/7592
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? yes
=> docs(glibc): add instructions on patching Envoy with glibc

terraform/windows.tf
`/aws/service/ami-windows-latest/Windows_Server-2019-English-Core-ContainersLatest` doesn't exist anymore.
I tested the new one with building envoy v1.25.10 and it succeeded.
It fixes: https://github.com/kumahq/envoy-builds/actions/runs/6478558480/job/17590518809
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits): 👍 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?: 👍
=> fix(terraform): update aws ssm parameter for windows ami

terraform/find-or-create-host.sh, terraform/macos.tf
We have problems building envoy on macOS 11 and according to envoy team, the latest envoy (v1.29.0) builds on macOS 12.
=> ci(macos): update macos to v12

terraform/main.tf, terraform/windows.tf
I've tried to use Base/Core image but they don't enable container feature by default. When I enable it it triggers VM restart which is not a good thing in CI. I am using ECS image which has feature enable and just install docker to make build works
=> chore(windows): install docker and reduce vm size

terraform/macos.tf
Otherwise we see errors from the userdata on startup:
```
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
```
Fixes _maybe_ https://github.com/kumahq/envoy-builds/issues/41
=> fix(darwin): remove pip3 install virtualenv

terraform/release-hosts.sh
We shouldn't fail the job if there are not ready to release hosts.
=> ci(.github): cleanup release-hosts

.github/workflows/build.yaml
The homebrew stuff on Darwin can take much longer.
=> ci: increase timeout on waiting for VMs

.github/workflows/build.yaml, scripts/dns_filter_resolver.h.patch, scripts/fetch_sources.sh, scripts/filter_test.cc.patch, scripts/rbac_filter.cc.patch, terraform/macos.tf, terraform/main.tf
This takes the changes from release-1.26 and applies them depending on `inputs.version`
=> fix: support building any version on default branch

.github/workflows/build-and-release.yaml, patches/v1.27-0001-dns-don-t-error-if-header-id-is-0.patch, patches/v1.28-0001-dns-don-t-error-if-header-id-is-0.patch, patches/v1.29-0001-dns-don-t-error-if-header-id-is-0.patch, patches/v1.30-0001-dns-don-t-error-if-header-id-is-0.patch, scripts/fetch_sources.sh
See https://github.com/envoyproxy/envoy/pull/35129
=> fix: add DNS error patch

terraform/build-windows.sh, terraform/windows.tf
We didn't apply patches for windows binaries. Now we are using `fetch_sources.sh` for a windows build
=> feat(windows): apply patch to windows binary

scripts/fetch_sources.sh
When there is no key in the map, the command was failing with 
```
scripts/fetch_sources.sh: linia 61: patches_per_version["v${major}.${minor}"]:  unbound variable 
```
added check which applies only to patches when they are defined
=> chore(build): fix the case when there is no key in the map

.github/workflows/build-and-release.yaml
Let's do this a little earlier.
=> ci(.github): run build and release before project report

.github/workflows/build-and-release.yaml, .github/workflows/release-on-schedule.yaml
Added a job that runs every day at midnight to check if a new version of Envoy has been published in the last 24 hours. If a new version is found, it triggers the build and release process automatically.
Limitation: Currently, only one version build can run at a time due to an issue with host allocation. If multiple jobs attempt to allocate the host simultaneously, the script may assign the same host to different jobs. This can lead to failures, as one job might use the host before another job gets the chance to do so.
=> chore(action): check if there is a new version of envoy and release

.github/workflows/release-on-schedule.yaml
We were missing `""` and didn't skip the job when no release
=> chore(gha): fix action to skip build on no change

.github/workflows/build.yaml, terraform/macos.tf
We need probably better version check since we should use `--copt=-mmacos-version-min=13.3 --host_copt=-mmacos-version-min=13.3"` for version main and newer
=> ci(mac): use osx 14 and newer compatibility

terraform/macos.tf
Not sure why, but on older system (mac-12) ready file wasn't created. When I install it twice it works and build is published
=> chore(mac): reinstall deps to make vm ready
