- terraform/main.tf
> refactor(terraform): use maps instead of ternary operator

- .github/workflows/build-and-release.yaml
Leave out the distro if it's equal to the OS.
> feat(.github): improve artifact names

- terraform/README.md
- terraform/main.tf
- terraform/windows.tf
> feat(terraform): add Windows support

- terraform/README.md
Needs more explicit instructions, just a hint for now
> docs(terraform): add hint about binary to README

- scripts/fetch_sources.sh
Easier to verify that it's really being applied
> chore: add -v to git apply

- .github/workflows/build.yaml
- scripts/build_darwin.sh
- terraform/macos.tf
> ci(macos): fix darwin builds

- .github/workflows/build-and-release.yaml
> chore(build): added missing fips

- .github/workflows/release-hosts.yaml
- terraform/release-hosts.sh
> chore(build): fail action when cannot release host

- .github/workflows/build-and-release.yaml
> chore(build): set main build version

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
- terraform/find-or-create-host.sh
- terraform/main.tf
* Added version to terraform to build more versions concurrently
* changed Linux host to a smaller
* fixed find host script
> chore(build): add version to terraform name

- terraform/windows.tf
Image was removed, switched to newer one
> chore(build): fix windows image

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
> chore(build): replace if with exclude

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- terraform/build-windows.sh
- terraform/find-or-create-host.sh
- terraform/main.tf
- terraform/wait-windows-host.sh
- terraform/windows.tf
> chore(build): backport build changes v1.27

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- terraform/build-windows.sh
- terraform/find-or-create-host.sh
- terraform/main.tf
- terraform/wait-windows-host.sh
- terraform/windows.tf
> chore(build): backport build changes v1.26

- terraform/macos.tf
> fix(darwin): try macos 13

- .github/workflows/build-and-release.yaml
Instead of `false` or `true` have "" or "fips"
> ci(.github): improve name of matrix jobs

- .github/workflows/build-and-release.yaml
> ci(.github): add release choice to run-name

- .github/workflows/build.yaml
> chore(darwin): increase timeout for connect to VM

- .github/workflows/build-and-release.yaml
so that people are less likely to run this improperly
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? yes
> ci(build): check input and additional information

- .github/workflows/build.yaml
Since last build it seems windows on aws works only with RSA so we need to add and if condition
> chore(windows): use rsa for windows

- .github/workflows/build.yaml
> chore(build): provide path to the key

- .github/workflows/build.yaml
- README.md
> chore(build): added readme and increased aws token time

- scripts/fetch_sources.sh
> fix(build): add new version of Envoy v1.33

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
- .github/workflows/release-hosts.yaml
- .github/workflows/release-on-schedule.yaml
Let's bind to specific version of ubuntu and add check for empty map to not trigger job everynight
> chore(build): upgrade ubuntu and check if version is not empty

- scripts/fetch_sources.sh
build is faling because of missing entry for the future release
> chore(build): add future version entry

- .github/workflows/build-and-release.yaml
- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/release-hosts.yaml
* pin version of the actions
* add version of envoy to the binary so we avoid conflict in the job release on schedule
> feat(release): add version to the artifact

- scripts/fetch_sources.sh
New version was released so we need to add new main version
> fix(build): add missing patch version

- .github/workflows/build-and-release.yaml
We want to download only specific version artifacts
> chore(build): download only specific version artifacts

- .github/workflows/build-and-release.yaml
Seems it broke finding specific version
> revert(package): don't use pattern
